---
# - name: Update repositories cache & upgrade packages
#   become: true
#   apt:
#     cache_valid_time: 86400  # One day
#   notify: apt upgrade

- name: update cache
  become: true
  raw: apt update

- name: Install apt, pip3
  become: true
  apt:
    name:
      - python3-pip
      - python3-dev
  notify: apt clean

- name: upgrade pip
  become: true
  pip:
    name: pip
    extra_args: --upgrade
  notify: clean cache
