- name: Check account already created
  become: true
  command: "sacctmgr -n -P show account {{ account.name }}"
  register: check
  failed_when: false
  changed_when: false
  ignore_errors: true

- name: Create account
  become: true
  command: "sacctmgr -i add account {{ account.name }}"
  when: check.stdout == ''
  