---
- name: set up the slurm
  hosts: 
    - cluster
  roles: 
    - role: slurm_base
      tags: slurm_base
  vars_files:
    - "vars/{{ cluster }}_slurm.yml"
    - "vars/{{ cluster }}_secrets.yml"

- name: set up slurm control node
  hosts: 
    - controlsrv
  gather_facts: no
  roles:
    - role: slurm_control
      tags: slurm_control
  vars_files:
    - "vars/{{ cluster  }}_slurm.yml"
    - "vars/{{ cluster }}_secrets.yml"

- name: set up slurm compute node
  hosts: 
    - computesrvs
  gather_facts: no
  roles:
    - role: slurm_compute
      tags: slurm_compute
  vars_files:
    - "vars/{{ cluster }}_slurm.yml"
